# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
require 'faker'

locations = Location.create([
  { name: "Boston", img_url: 'https://i.imgur.com/35FTluS.png'},
  {name: "San Francisco", img_url: "https://imgur.com/93mSUwz.png" },
  {name: "Miami", img_url: "https://imgur.com/akv5g6i.png"},
  {name: "Edinburgh", img_url: "https://imgur.com/sqon1fh.png" },
  {name: "Budapest", img_url: "https://imgur.com/6NcUHoW.png" },
  {name: "Istanbul", img_url: "https://imgur.com/k8As83O.png" },
  {name: "Bratislava", img_url: "https://imgur.com/XrhNcIG.png"},
  {name: "Sonoma", img_url: "https://imgur.com/BkrKkJm.png" },
  {name: "Rome", img_url: "https://imgur.com/0aNRYn4.png" },
  {name: "Unknown", img_url: "https://imgur.com/beBRku6.png" },
  {name: "Portland, OR", img_url: "https://imgur.com/Di7pMUp.png"},
  {name: "Portland, ME", img_url: "https://imgur.com/JeOPtZJ.png"},
  {name: "Paris", img_url: "https://imgur.com/jZs6WKz.png"}
])

users_url = ["https://randomuser.me/api/portraits/thumb/men/63.jpg",
"https://randomuser.me/api/portraits/thumb/men/42.jpg",
"https://randomuser.me/api/portraits/thumb/women/63.jpg",
"https://randomuser.me/api/portraits/thumb/women/6.jpg",
"https://randomuser.me/api/portraits/thumb/women/69.jpg",
"https://randomuser.me/api/portraits/thumb/men/2.jpg",
"https://randomuser.me/api/portraits/thumb/men/11.jpg",
"https://randomuser.me/api/portraits/thumb/men/97.jpg",
"https://randomuser.me/api/portraits/thumb/women/2.jpg",
"https://randomuser.me/api/portraits/thumb/women/9.jpg",
"https://randomuser.me/api/portraits/thumb/men/26.jpg",
"https://randomuser.me/api/portraits/thumb/women/85.jpg",
"https://randomuser.me/api/portraits/thumb/women/91.jpg",
"https://randomuser.me/api/portraits/thumb/men/85.jpg",
"https://randomuser.me/api/portraits/thumb/men/95.jpg",
"https://randomuser.me/api/portraits/thumb/men/8.jpg",
"https://randomuser.me/api/portraits/thumb/women/43.jpg",
"https://randomuser.me/api/portraits/thumb/men/46.jpg",
"https://randomuser.me/api/portraits/thumb/men/37.jpg",
"https://randomuser.me/api/portraits/thumb/women/26.jpg",
"https://randomuser.me/api/portraits/thumb/men/17.jpg",
"https://randomuser.me/api/portraits/thumb/women/17.jpg",
"https://randomuser.me/api/portraits/thumb/women/6.jpg",
"https://randomuser.me/api/portraits/thumb/men/55.jpg",
"https://randomuser.me/api/portraits/thumb/women/83.jpg",
"https://randomuser.me/api/portraits/thumb/women/4.jpg",
"https://randomuser.me/api/portraits/thumb/men/62.jpg",
"https://randomuser.me/api/portraits/thumb/women/66.jpg",
"https://randomuser.me/api/portraits/thumb/women/64.jpg",
"https://randomuser.me/api/portraits/thumb/women/27.jpg",
"https://randomuser.me/api/portraits/thumb/women/14.jpg",
"https://randomuser.me/api/portraits/thumb/men/67.jpg",
"https://randomuser.me/api/portraits/thumb/women/44.jpg",
"https://randomuser.me/api/portraits/thumb/women/57.jpg",
"https://randomuser.me/api/portraits/thumb/men/1.jpg",
"https://randomuser.me/api/portraits/thumb/women/47.jpg",
"https://randomuser.me/api/portraits/thumb/women/0.jpg",
"https://randomuser.me/api/portraits/thumb/women/68.jpg",
"https://randomuser.me/api/portraits/thumb/women/90.jpg",
"https://randomuser.me/api/portraits/thumb/women/8.jpg",
"https://randomuser.me/api/portraits/thumb/men/55.jpg",
"https://randomuser.me/api/portraits/thumb/men/41.jpg",
"https://randomuser.me/api/portraits/thumb/women/75.jpg",
"https://randomuser.me/api/portraits/thumb/men/14.jpg",
"https://randomuser.me/api/portraits/thumb/men/12.jpg",
"https://randomuser.me/api/portraits/thumb/men/54.jpg",
"https://randomuser.me/api/portraits/thumb/men/81.jpg",
"https://randomuser.me/api/portraits/thumb/men/73.jpg",
"https://randomuser.me/api/portraits/thumb/women/12.jpg",
"https://randomuser.me/api/portraits/thumb/women/68.jpg",
"https://randomuser.me/api/portraits/thumb/women/86.jpg",
"https://randomuser.me/api/portraits/thumb/women/63.jpg",
"https://randomuser.me/api/portraits/thumb/men/70.jpg",
"https://randomuser.me/api/portraits/thumb/men/5.jpg",
"https://randomuser.me/api/portraits/thumb/women/36.jpg",
"https://randomuser.me/api/portraits/thumb/women/65.jpg",
"https://randomuser.me/api/portraits/thumb/women/29.jpg",
"https://randomuser.me/api/portraits/thumb/men/1.jpg",
"https://randomuser.me/api/portraits/thumb/women/92.jpg",
"https://randomuser.me/api/portraits/thumb/women/50.jpg",
"https://randomuser.me/api/portraits/thumb/women/58.jpg",
"https://randomuser.me/api/portraits/thumb/men/22.jpg",
"https://randomuser.me/api/portraits/thumb/men/6.jpg",
"https://randomuser.me/api/portraits/thumb/men/26.jpg",
"https://randomuser.me/api/portraits/thumb/women/53.jpg",
"https://randomuser.me/api/portraits/thumb/women/21.jpg",
"https://randomuser.me/api/portraits/thumb/women/80.jpg",
"https://randomuser.me/api/portraits/thumb/women/18.jpg",
"https://randomuser.me/api/portraits/thumb/women/75.jpg",
"https://randomuser.me/api/portraits/thumb/women/41.jpg",
"https://randomuser.me/api/portraits/thumb/women/30.jpg",
"https://randomuser.me/api/portraits/thumb/women/34.jpg",
"https://randomuser.me/api/portraits/thumb/men/20.jpg",
"https://randomuser.me/api/portraits/thumb/women/75.jpg",
"https://randomuser.me/api/portraits/thumb/men/21.jpg",
"https://randomuser.me/api/portraits/thumb/women/88.jpg",
"https://randomuser.me/api/portraits/thumb/women/13.jpg",
"https://randomuser.me/api/portraits/thumb/men/46.jpg",
"https://randomuser.me/api/portraits/thumb/women/15.jpg",
"https://randomuser.me/api/portraits/thumb/men/11.jpg",
"https://randomuser.me/api/portraits/thumb/men/18.jpg",
"https://randomuser.me/api/portraits/thumb/women/46.jpg",
"https://randomuser.me/api/portraits/thumb/women/72.jpg",
"https://randomuser.me/api/portraits/thumb/men/34.jpg",
"https://randomuser.me/api/portraits/thumb/men/2.jpg",
"https://randomuser.me/api/portraits/thumb/women/1.jpg",
"https://randomuser.me/api/portraits/thumb/men/63.jpg",
"https://randomuser.me/api/portraits/thumb/women/75.jpg",
"https://randomuser.me/api/portraits/thumb/women/81.jpg",
"https://randomuser.me/api/portraits/thumb/women/60.jpg",
"https://randomuser.me/api/portraits/thumb/men/24.jpg",
"https://randomuser.me/api/portraits/thumb/women/40.jpg",
"https://randomuser.me/api/portraits/thumb/men/53.jpg",
"https://randomuser.me/api/portraits/thumb/men/39.jpg",
"https://randomuser.me/api/portraits/thumb/women/9.jpg",
"https://randomuser.me/api/portraits/thumb/men/50.jpg",
"https://randomuser.me/api/portraits/thumb/men/39.jpg",
"https://randomuser.me/api/portraits/thumb/women/55.jpg",
"https://randomuser.me/api/portraits/thumb/women/77.jpg",
"https://randomuser.me/api/portraits/thumb/men/21.jpg",
"https://randomuser.me/api/portraits/thumb/women/57.jpg",
"https://randomuser.me/api/portraits/thumb/women/21.jpg",
"https://randomuser.me/api/portraits/thumb/men/45.jpg",
"https://randomuser.me/api/portraits/thumb/men/20.jpg",
"https://randomuser.me/api/portraits/thumb/women/55.jpg",
"https://randomuser.me/api/portraits/thumb/women/79.jpg",
"https://randomuser.me/api/portraits/thumb/men/11.jpg",
"https://randomuser.me/api/portraits/thumb/men/96.jpg",
"https://randomuser.me/api/portraits/thumb/men/54.jpg",
"https://randomuser.me/api/portraits/thumb/men/41.jpg",
"https://randomuser.me/api/portraits/thumb/women/77.jpg",
"https://randomuser.me/api/portraits/thumb/women/0.jpg",
"https://randomuser.me/api/portraits/thumb/men/46.jpg",
"https://randomuser.me/api/portraits/thumb/men/57.jpg",
"https://randomuser.me/api/portraits/thumb/women/74.jpg",
"https://randomuser.me/api/portraits/thumb/men/63.jpg",
"https://randomuser.me/api/portraits/thumb/women/4.jpg",
"https://randomuser.me/api/portraits/thumb/women/11.jpg",
"https://randomuser.me/api/portraits/thumb/women/84.jpg",
"https://randomuser.me/api/portraits/thumb/women/57.jpg",
"https://randomuser.me/api/portraits/thumb/women/32.jpg",
"https://randomuser.me/api/portraits/thumb/women/61.jpg",
"https://randomuser.me/api/portraits/thumb/men/17.jpg",
"https://randomuser.me/api/portraits/thumb/men/18.jpg",
"https://randomuser.me/api/portraits/thumb/women/48.jpg",
"https://randomuser.me/api/portraits/thumb/men/69.jpg",
"https://randomuser.me/api/portraits/thumb/men/4.jpg",
"https://randomuser.me/api/portraits/thumb/men/4.jpg",
"https://randomuser.me/api/portraits/thumb/men/40.jpg",
"https://randomuser.me/api/portraits/thumb/men/30.jpg",
"https://randomuser.me/api/portraits/thumb/women/7.jpg",
"https://randomuser.me/api/portraits/thumb/men/84.jpg",
"https://randomuser.me/api/portraits/thumb/women/83.jpg",
"https://randomuser.me/api/portraits/thumb/women/20.jpg",
"https://randomuser.me/api/portraits/thumb/men/27.jpg",
"https://randomuser.me/api/portraits/thumb/women/32.jpg",
"https://randomuser.me/api/portraits/thumb/men/81.jpg",
"https://randomuser.me/api/portraits/thumb/women/34.jpg",
"https://randomuser.me/api/portraits/thumb/women/90.jpg",
"https://randomuser.me/api/portraits/thumb/men/28.jpg",
"https://randomuser.me/api/portraits/thumb/women/23.jpg",
"https://randomuser.me/api/portraits/thumb/men/83.jpg",
"https://randomuser.me/api/portraits/thumb/women/43.jpg",
"https://randomuser.me/api/portraits/thumb/women/78.jpg",
"https://randomuser.me/api/portraits/thumb/men/3.jpg",
"https://randomuser.me/api/portraits/thumb/women/77.jpg",
"https://randomuser.me/api/portraits/thumb/women/67.jpg",
"https://randomuser.me/api/portraits/thumb/women/26.jpg",
"https://randomuser.me/api/portraits/thumb/men/90.jpg",
"https://randomuser.me/api/portraits/thumb/men/62.jpg"
 ]

 users = []
 users.push(User.create({username: "nick", password: "123456", image_url: "https://imgur.com/aLAPKce.jpg" , location_id: 2}))

0.upto(150) do |idx|
  users.push(User.create({username: Faker::Internet.user_name(6..9), password: "123456", image_url: users_url[idx], location_id: (1 + rand(13))}))
end


User.create({username: 'NiartenyaW', password: "sweetawesome", image_url: 'https://avatars2.githubusercontent.com/u/8084693?s=400&v=4'})
